name: Continuous Integration

on: [pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Install Dependencies
              run: npm install

            - name: Run Build
              run: CI=false npm run build
