name: Continuous Deployment

on:
    push:
        branches:
            - development

jobs:
    deploy:
        name: Deploy on github pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"

            - run: npm install
              env:
                  REACT_APP_API_KEY: ${{ secrets.API_KEY }}

            - run: npm run build

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v1
              with:
                  target_branch: gh-pages
                  build_dir: build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
